name: Build and Push Docker Image

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Log in to GitHub Container Registry (GHCR)
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_PAT }}

      # Step 3: Build and push Docker image
      - name: Build and push Docker image
        run: |
          IMAGE_NAME=$(basename "${{ github.repository }}")  # Extract repo name only
          OWNER=$(dirname "${{ github.repository }}")         # Extract owner

          IMAGE="ghcr.io/${OWNER}/${IMAGE_NAME}"
          SHA_TAG="${{ github.sha }}"

          echo "Building and pushing ${IMAGE}:${SHA_TAG}"

          docker build -t "${IMAGE}:${SHA_TAG}" .
          docker push "${IMAGE}:${SHA_TAG}"

          # Also tag as latest
          docker tag "${IMAGE}:${SHA_TAG}" "${IMAGE}:latest"
          docker push "${IMAGE}:latest"
